from typing import Protocol, Callable, Optional
from enum import Enum


class LogLevel(Enum):
    INFO = "info"
    SUCCESS = "success"
    WARNING = "warning"
    ERROR = "error"
    DEBUG = "debug"


class LogCategory(Enum):
    SYSTEM = "system"
    USER = "user"
    TOOL = "tool"
    MODEL = "model"
    ASSISTANT = "assistant"

    def display_name(self) -> str:
        # You can keep your i18n here if you want
        from gepetto import config
        _ = config._
        labels = {
            LogCategory.SYSTEM: _("System"),
            LogCategory.USER: _("User"),
            LogCategory.TOOL: _("Tool"),
            LogCategory.MODEL: _("Model"),
            LogCategory.ASSISTANT: _("Assistant"),
        }
        return labels[self]


class StatusPanel(Protocol):
    def ensure_shown(self) -> None: ...
    def form_closed(self) -> None: ...
    def on_form_ready(self) -> None: ...

    def set_model(self, model_name: str) -> None: ...
    def set_status(self, text: str, *, busy: bool = False, error: bool = False) -> None: ...

    def set_stop_callback(self, callback: Optional[Callable[[], None]]) -> None: ...
    def reset_stop(self) -> None: ...
    def has_stop_callback(self) -> bool: ...
    def request_stop(self) -> None: ...

    def start_stream(self) -> None: ...
    def append_stream(self, chunk: str) -> None: ...
    def finish_stream(self, final_text: str) -> None: ...
    def append_reasoning(self, chunk: str) -> None: ...
    def finish_reasoning(self) -> None: ...

    def log_user(self, text: str) -> None: ...
    def log(
            self,
            message: str,
            *,
            category: LogCategory = LogCategory.SYSTEM,
            level: LogLevel = LogLevel.INFO,
    ) -> None: ...
    def log_request_started(self) -> str: ...
    def log_request_finished(self, elapsed_seconds: float) -> str: ...

    def mark_error(self, message: str) -> None: ...
    def clear_log(self) -> None: ...
    def close(self) -> None: ...
